services:
  - type: web
    name: lector-ensayos
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --timeout 120 --workers 1
    envVars:
      - key: PYTHON_VERSION
        value: "3.11"
